### ISSUE TITLE
"Copy JSX" button on heroicons.com copies SVG instead

### ISSUE THREAD

**Issue by ericvanular** [tailwindlabs/heroicons#862] opened 2022-10-17 20:05 UTC
Currently when you click the "Copy JSX" button that appears on hover over any icons on heroicons.com, the SVG is copied instead. Tested on Firefox, Safari, & Chrome.

**Comment by adamwathan** [comment] 2022-10-17 21:10
Hey! Closing as duplicate of https://github.com/tailwindlabs/heroicons/issues/840

**Closed by adamwathan** 2022-10-17 21:10 UTC
