### ISSUE TITLE
I want you to support stroke-width in heroicons/react

### ISSUE THREAD

**Issue by ru88s** [tailwindlabs/heroicons#263] opened 2021-04-24 02:48 UTC
```
import { BookOpenIcon } from "@heroicons/react/outline";

<BookOpenIcon className="w-10 stroke-1"/>
```

stroke-1 does not work.
Is there a way to adjust the stroke-width?

**Comment by sanderfish** [comment] 2021-05-03 08:12
Duplicate of https://github.com/tailwindlabs/heroicons/issues/241

**Comment by ukasyah99** [comment] 2021-07-25 08:17
> Is there a way to adjust the stroke-width?

Yes, it's pretty simple. You just need to write some css as follows:

```css

/* Set heroicon's stroke width */
.heroicon-sw-2 path {
  stroke-width: 2 !important;
}
.heroicon-sw-1\.75 path {
  stroke-width: 1.75 !important;
}
.heroicon-sw-1\.5 path {
  stroke-width: 1.5 !important;
}
.heroicon-sw-1\.2 path {
  stroke-width: 1.2 !important;
}
```

Finally:

```js
<BookOpenIcon className="w-10 h-10 heroicon-sw-1.5" />
```

Although the above example uses the jsx version, it can also be applied to the svg version  #241 .

**Comment by bradlc** [comment] 2022-02-22 15:30
Duplicate of #241

**Closed by bradlc** 2022-02-22 15:30 UTC

**Comment by Fabian-Andres** [comment] 2022-08-24 00:48
With Tailwind ^3.0 you could use arbitrary properties like this:

```
<BookOpenIcon className="w-10 h-10 [&>path]:stroke-[2]" />
```
 you can even use `stroke-[2px]` px, rem, em, etc.

**Comment by andrewsmithdesign** [comment] 2024-06-18 09:26
Heya for anyone browsing this, I just got it to work without the [&>path]: attribute, just straight stroke-1 and stroke-2 etc worked (as well as stroke-[1.5] etc)

`<DocumentTextIcon className="h-10 w-10 stroke-1 text-gray-400" />`

**Comment by hashirshoaeb** [comment] 2024-12-03 04:20
`stroke-1` from tailwind was not working for svg, untill i added `stroke="currentColor"` in svg
