### ISSUE TITLE
nuxt3 build 'direct import' errors with import from @heroicons/vue/outline in vue component

### ISSUE THREAD

**Issue by oliviermills** [tailwindlabs/heroicons#643] opened 2022-03-13 00:19 UTC
dev works fine, but breaks on build for nuxt v3

<img width="531" alt="image" src="https://user-images.githubusercontent.com/6075303/158039463-774978f8-2cae-4184-ab8e-5aa07e971c63.png">

This repo is the base sample from vercel nuxt3 (works fine until you try @heroicons
clone [https://github.com/oliviermills/test-nuxt3](https://github.com/oliviermills/test-nuxt3)

1. `yarn install`
2. `yarn build`
3. `yarn start` (to run the build)

**Comment by arnauddoub** [comment] 2022-03-15 11:14
same problem

**Comment by reinink** [comment] 2022-03-25 17:35
Hey folks! This appears to be a duplicate of issue #564, which includes a couple solutions on how to fix this 👍

**Closed by reinink** 2022-03-25 17:35 UTC
