### ISSUE TITLE
[Vue] Issue when building with version 1.0.5

### ISSUE THREAD

**Issue by nmathew98** [tailwindlabs/heroicons#577] opened 2022-01-13 06:20 UTC
Build errors as below when building with version 1.0.5 of the Vue package.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/55116576/149276087-b1563ec4-98ea-4609-bacf-909bb0266dd9.png">

**Comment by reinink** [comment] 2022-01-15 15:07
Hey there! This looks like a duplicate of #516, and from what I understand there this issue has been resolved in the latest version of Volar. See here as well: https://github.com/johnsoncodehk/volar/issues/574

Hope that helps 👍

**Closed by reinink** 2022-01-15 15:07 UTC

**Comment by nmathew98** [comment] 2022-01-15 21:11
Thank you!
